
DROP DATABASE IF EXISTS `DVDManager`;

CREATE DATABASE IF NOT EXISTS DVDManager;
USE DVDManager;

CREATE TABLE IF NOT EXISTS USERS (
	USER_ID INT NOT NULL AUTO_INCREMENT,
    FULL_NAME VARCHAR(100) NOT NULL,
    LOGIN VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(250) NOT NULL,
    ACTIVE INT NOT NULL,
    PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS DISKS (
	DISK_ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(250) NOT NULL,
    USER_ID INT NOT NULL,
    PRIMARY KEY (Disk_ID),
    INDEX FK_DISKS_USERS_idx (USER_ID ASC),
    CONSTRAINT FK_Disks_Users
		FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS TAKENITEM (
	USER_ID INT NOT NULL,
    DISK_ID INT NOT NULL,
    START_DATE DATETIME NOT NULL,
    RENTED_STATUS TINYINT(1) NOT NULL,
    PRIMARY KEY (USER_ID, DISK_ID, RENTED_STATUS),
    INDEX FK_TAKENITEM_DISKS_idx (DISK_ID ASC),
    INDEX FK_TAKENITEM_USERS_idx (USER_ID ASC),
	CONSTRAINT FK_TAKENITEM_USERS
		FOREIGN KEY (USER_ID)
		REFERENCES USERS (USER_ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
	CONSTRAINT FK_TAKENITEM_DISKS
		FOREIGN KEY (DISK_ID)
		REFERENCES DISKS (DISK_ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);